AllCops:
  NewCops: enable
  SuggestExtensions: false

# modified rules for spec/test files
Metrics/BlockLength: &specs_disable
  Enabled: false
  Exclude: 
    - spec/**_spec.rb
Layout/EmptyLinesAroundBlockBody:
  <<: *specs_disable
Style/BlockDelimiters:
  <<: *specs_disable
Style/MixinUsage:
  <<: *specs_disable
Layout/SpaceInsideParens:
  <<: *specs_disable
Style/FrozenStringLiteralComment:
  Enabled: false

# allow with ( ) missing
# def method param1, param2
Style/MethodDefParentheses:
  Enabled: false

# allow indent of closing HERE_DOC
# do
#   variable = <<~HERE_DOC
#     ```
#     contents
#     ```
#     HERE_DOC
# end
Layout/ClosingHeredocIndentation:
  Enabled: false
